# Form implementation generated from reading ui file 'proj_mol.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
import numpy as np

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(658, 407)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 661, 411))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 181, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(210, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(210, 180, 111, 31))
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 141, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(220, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 130, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(380, 40, 251, 291))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Molino.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")

        
        self.pushButton.clicked.connect(self.click_btn_tab1)


        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 221, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 221, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 130, 221, 17))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 160, 221, 17))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 100, 221, 17))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 260, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(230, 30, 91, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(230, 60, 91, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_4.setGeometry(QtCore.QRect(230, 90, 91, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(230, 120, 91, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(230, 150, 91, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 300, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 320, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 300, 113, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 320, 113, 20))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 270, 131, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 270, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(120, 200, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_7.setGeometry(QtCore.QRect(230, 190, 91, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(390, 10, 211, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("porcentaje_bolas_start.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")


        self.pushButton_2.clicked.connect(self.click_btn_tab2)


        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def click_btn_tab1(self):
        textInput_diametroMolino = self.lineEdit.text()
        Diam_mol = float(textInput_diametroMolino)
        textInput_alturaCarga = self.lineEdit_4.text()
        h_carga = float(textInput_alturaCarga)
        alpha = 2*np.arccos(2*(h_carga-Diam_mol/2)/Diam_mol)
        area_arc=alpha/8*Diam_mol**2
        altura = h_carga-Diam_mol/2
        base = 2*(Diam_mol/2*np.sin(alpha/2))
        triangulo=base*altura/2
        carga=area_arc-triangulo
        carga_1=(Diam_mol/2)**2/2*(alpha-np.sin(alpha))
        area_T=np.pi*Diam_mol**2/4
        self.textBrowser.setText(str(carga_1/area_T*100)[:8])

    def click_btn_tab2(self):
        textInput_diametroMolino = self.lineEdit_5.text()
        Diam_mol = float(textInput_diametroMolino)
        textInput_largoMolino = self.lineEdit_6.text()
        Largo_mol = float(textInput_largoMolino)
        Volumen_molino = Largo_mol*np.pi*Diam_mol*Diam_mol
        textInput_carga = self.lineEdit_7.text()
        carga_mol = float(textInput_carga)
        Volumen_carga = Volumen_molino*carga_mol/100
        porosidad = 0.35
        parte_bolas = 1-porosidad
        Volumen_bolas = Volumen_carga*parte_bolas
        densidad = 7.85 # ton/m^3
        ###
        m_b= densidad*Volumen_bolas #toneladas
        self.textBrowser_7.setText(str(m_b)[:8])
        ###
        diametro_bolas = np.array([3,2.5,2,1.5,1])
        checked=np.array([1,1,1,1,1])
        if self.checkBox.isChecked()==False:
            checked[0]=0
        else:
            checked[0]=1
        if self.checkBox_2.isChecked()==False:
            checked[1]=0
        else:
            checked[1]=1
        if self.checkBox_3.isChecked()==False:
            checked[3]=0
        else:
            checked[3]=1
        if self.checkBox_4.isChecked()==False:
            checked[4]=0
        else:
            checked[4]=1
        if self.checkBox_5.isChecked()==False:
            checked[2]=0
        else:
            checked[2]=1
        bolas_sel=checked*diametro_bolas
        no_zero=np.nonzero(bolas_sel)
        bolas_fil=bolas_sel[no_zero]
        bola_max=np.max(bolas_sel)
        bola_min=np.min(bolas_sel)
        X0=bola_max*np.ones(len(bolas_fil))
        Xf=bola_min*np.ones(len(bolas_fil))
        inter_porte=[]
        for i in range(len(bolas_fil)-1):
            Xi=(bolas_fil[i]*bolas_fil[i+1])**0.5
            inter_porte.append(Xi)
        inter_porte.append(1)
        Xif=np.array(inter_porte)
        Porcentaje_Distribucion=(Xif**4-Xf**4)/(X0**4-Xf**4)*100
        Porcentaje_Retenido_list=[]
        for i in range(len(Porcentaje_Distribucion)):
            if i == 0:
                Pc_R=100-Porcentaje_Distribucion[i]
                Porcentaje_Retenido_list.append(Pc_R)
            else:
                Pc_R=Porcentaje_Distribucion[i-1]-Porcentaje_Distribucion[i]
                Porcentaje_Retenido_list.append(Pc_R)
        c=0
        Porcentaje_Retenido_newList=[]
        for i in checked:
            if i!=0:
                Porcentaje_Retenido_newList.append(Porcentaje_Retenido_list[c])
                c=c+1
            else:
                Porcentaje_Retenido_newList.append(0)
        

        self.textBrowser_2.setText(str(Porcentaje_Retenido_newList[0]/100*m_b)[:8])
        self.textBrowser_3.setText(str(Porcentaje_Retenido_newList[1]/100*m_b)[:8])
        self.textBrowser_4.setText(str(Porcentaje_Retenido_newList[2]/100*m_b)[:8])
        self.textBrowser_5.setText(str(Porcentaje_Retenido_newList[3]/100*m_b)[:8])
        self.textBrowser_6.setText(str(Porcentaje_Retenido_newList[4]/100*m_b)[:8])

        Db=['D= 3[in]','D= 2.5[in]','D= 2[in]','D= 1.5[in]','D= 1[in]']
        fig = plt.figure(figsize =(4,4))
        patches, text = plt.pie(Porcentaje_Retenido_newList, startangle=90)
        plt.legend(patches, Db, loc="best")
        plt.axis('equal')
        plt.tight_layout()
        plt.savefig('porcentaje_bolas.png')
        self.label_4.setPixmap(QtGui.QPixmap("porcentaje_bolas.png"))



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Molino"))
        self.label_2.setText(_translate("Form", "Diametro interior de molino (m)"))
        self.lineEdit.setText(_translate("Form", "7.06"))
        self.label_5.setText(_translate("Form", "% de carga del molino"))
        self.pushButton.setText(_translate("Form", "Calcular"))
        self.lineEdit_4.setText(_translate("Form", "4.39"))
        self.label_6.setText(_translate("Form", "Distancia entre techo y carga (m)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Carga de molino"))
        self.checkBox.setText(_translate("Form", "Maximo tamaño de bola (3 in)"))
        self.checkBox_2.setText(_translate("Form", "Siguente tamaño de bola (2.5 in)"))
        self.checkBox_3.setText(_translate("Form", "Siguiente tamaño de bola (1.5 in)"))
        self.checkBox_4.setText(_translate("Form", "Minimo tamaño de bola (1 in)"))
        self.checkBox_5.setText(_translate("Form", "Siguente tamaño de bola (2 in)"))
        self.label.setText(_translate("Form", "Tamaños disponibles de la empresa"))
        self.pushButton_2.setText(_translate("Form", "Calcular"))
        self.label_3.setText(_translate("Form", "Diametro Molino (m)"))
        self.label_7.setText(_translate("Form", "Largo Molino (m)"))
        self.lineEdit_5.setText(_translate("Form", "7.06"))
        self.lineEdit_6.setText(_translate("Form", "10.5"))
        self.label_8.setText(_translate("Form", "% de carga en Molino"))
        self.lineEdit_7.setText(_translate("Form", "34"))
        self.label_9.setText(_translate("Form", "Total (ton)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tonelaje de bolas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
